# GitHub Repository Settings
# This file can be used with Probot Settings app or as a reference for manual configuration
# https://github.com/probot/settings

repository:
  # Repository settings
  name: automation-exercise
  description: AI Automation Mastery - Training Exercises
  homepage: https://louischancly.github.io/automation-exercises/

  # Repository features
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  # Update the default branch if needed
  default_branch: main

  # Allow squash merge, rebase merge, and merge commits
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  # Automatically delete head branches after PRs are merged
  delete_branch_on_merge: true

# Branch protection rules
branches:
  - name: main
    # Require pull request reviews before merging
    protection:
      # Require at least one review
      required_pull_request_reviews:
        # Dismiss stale reviews when new commits are pushed
        dismiss_stale_reviews: true
        # Require review from Code Owners
        require_code_owner_reviews: false
        # Number of required approving reviews (0 means anyone can merge via PR)
        required_approving_review_count: 0
        # Restrict who can dismiss pull request reviews
        dismissal_restrictions:
          users: []
          teams: []

      # Require status checks to pass before merging
      required_status_checks:
        # Require branches to be up to date before merging
        strict: true
        # Status checks that must pass
        contexts: []

      # Enforce restrictions for administrators
      # Set to false to allow admins to bypass branch protection
      # Set to true to enforce rules even for admins/owners
      enforce_admins: false

      # Restrict who can push to matching branches
      # Only users/teams listed here can push directly (bypassing PRs)
      # Leave empty to allow admins/owners only
      restrictions:
        users: []
        teams: []
        apps: []

      # Require linear history (no merge commits)
      required_linear_history: false

      # Allow force pushes (not recommended for main branch)
      allow_force_pushes: false

      # Allow deletions of the protected branch
      allow_deletions: false

      # Require signed commits
      required_signatures: false
