# Markdownlint configuration
# Documentation: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# Line length
MD013: false  # Disabled - long lines are OK for documentation

# Headings
MD024: false  # Allow duplicate headings (for consistent challenge structure)
MD025: false  # Allow multiple top-level headings for documentation
MD022: true  # Headings should be surrounded by blank lines
MD026: true  # No trailing punctuation in headings

# Lists
MD028: false  # Allow blank lines in blockquotes
MD032: true  # Lists should be surrounded by blank lines
MD030:
  ul_single: 1
  ul_multi: 1
  ol_single: 1
  ol_multi: 1

# Code blocks
MD031: true  # Fenced code blocks should be surrounded by blank lines
MD040: false  # Allow code blocks without language specification
MD046:
  style: fenced  # Use fenced code blocks instead of indented

# Whitespace
MD009: true  # No trailing spaces
MD010: true  # No hard tabs
MD012:
  maximum: 2  # Maximum number of consecutive blank lines

# Links and images
MD042: false  # Allow empty links (for placeholder Discord links etc)
MD045: true  # Images should have alt text

# HTML
MD033: false  # Allow inline HTML

# Files
MD047: true  # Files should end with a single newline character

# Inline code
MD038: false  # Spaces inside code span elements (disabled for flexibility)

# Emphasis
MD036: false  # Emphasis used instead of a heading (disabled for flexibility)

# UK English spelling - These words are correctly spelled
MD043: false  # Required heading structure (disabled for flexibility)
MD044: false  # Proper names should have the correct capitalization (disabled)
