# GitHub Pages Configuration for AI Automation Mastery Course

title: AI Automation Mastery
description: Hands-on automation exercises for future employability
author: Louis Chan
email: louixchan.cly@gmail.com

# GitHub Pages settings
domain: louischancly.github.io
url: https://louischancly.github.io
baseurl: /automation-exercises

# Theme configuration
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light

# Just the Docs settings
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Aux links for top navigation
aux_links:
  "GitHub":
    - "//github.com/louischancly/automation-exercises"

# Footer content
footer_content: "Copyright &copy; 2024 AI Automation Mastery. Built with Jekyll and Just the Docs."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Callouts configuration
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Custom styles to avoid Sass deprecation warnings
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true  # Suppress deprecation warnings from dependencies

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Mermaid diagram support
mermaid:
  enable: true
  version: "10.6.1"

# Collections for exercises
collections:
  exercises:
    output: true
    permalink: /exercises/:path/
    order:
      - 01-email-classification.md
      - 02-social-media-monitor.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "exercises"
    values:
      layout: "exercise"
      toc: true
      toc_sticky: true
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /guides/setup/
  - title: Exercises
    url: /exercises/
  - title: Resources
    url: /resources/

# Exercise categories
exercise_categories:
  - title: "Foundation"
    description: "Core automation concepts"
    exercises: [1, 2, 3, 4, 5]
  - title: "AI Integration"
    description: "Working with LLMs and AI APIs"
    exercises: [6, 7, 8, 9, 10]
  - title: "Advanced Workflows"
    description: "Complex multi-step automations"
    exercises: [11, 12, 13, 14, 15]
  - title: "Industry Applications"
    description: "Real-world business scenarios"
    exercises: [16, 17, 18, 19, 20]

# Search
search: true
search_full_content: true

# Analytics (add your tracking ID)
google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
