# GitHub Actions workflow for PR preview deployments
# Creates temporary preview deployments for pull requests

name: PR Preview Deployment

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/pr-preview.yml'
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: ./docs

      - name: Build Jekyll site
        run: |
          cd docs
          bundle exec jekyll build --baseurl "/automation-exercises/pr-${{ github.event.number }}"
        env:
          JEKYLL_ENV: development

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-preview-${{ github.event.number }}
          path: ./docs/_site
          retention-days: 7

      - name: Comment PR with preview info
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const preview_url = `https://${context.repo.owner}.github.io/automation-exercises/pr-${issue_number}/`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `## 🔍 Preview Build Ready\n\nYour changes have been built successfully!\n\n### Build Information:\n- **PR Number:** #${issue_number}\n- **Build Status:** ✅ Success\n- **Artifact:** jekyll-preview-${issue_number}\n\nNote: This is a build preview only. The actual deployment happens after merge to main.`
            });
